### PR TITLE
FriendsOfJakarta-2021-01-27

### PR DESCRIPTION
**Pull request by cesarhernandezgt**

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
Solves #62

**Comment by cesarhernandezgt** [comment]
Hi @hudsonkelly83 
Can you please upload this video to youtube according to #62 so we can then remove the video from the repository?

**Comment by hudsonkelly83** [comment]
Uploaded to YouTube: https://youtu.be/oCfrMSQKWn4

**Comment by cesarhernandezgt** [comment]
Thank you @hudsonkelly83 . closing the PR instead of merging the PR to save space on the repository Github LFS.

**Pull request closed without merging**
