### PR TITLE
Added Synergy JakartaEE and MicroProfile art work

### PR DESCRIPTION
**Pull request by BaptisteMeynier**
Signed-off-by: Baptiste Meynier baptiste.meynier@gmail.com

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
Thank you, this PR solves #1

**Comment by TanjaObradovic** [comment]
The image looks OK at the first glance, but @karenmcnaughton will send an email to `license@eclipse.org` to make sure, and one of us will get back to you here. 
Going forward, anyone from the community can also consult `license@eclipse.org` when questions like this come up.

**Comment by BaptisteMeynier** [comment]
Thx @TanjaObradovic, I'm available if picture need some modifications or updates.

**Review by karenmcnaughton — COMMENTED** [review]
Hello--to update you from the Eclipse side, legal has reviewed and does not see any issue with the use of the (R). This is approved for usage. Thank you!

**Comment by cesarhernandezgt** [comment]
Thank you @karenmcnaughton and @TanjaObradovic for the review and follow-up.
I'm going to merge now the file so then this can be presented to the working groups before social media distribution and amplification via this repository.

**Review by cesarhernandezgt — APPROVED** [review]

**Pull request merged**
